<?php
/**
 * EcedoERPCRMInterfaceApiSmartDevice
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo.ERP.UI.Web Core
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1-core
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * EcedoERPCRMInterfaceApiSmartDevice Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EcedoERPCRMInterfaceApiSmartDevice implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Ecedo.ERP.CRM.Interface.Api.SmartDevice';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'smart_device_id' => 'string',
        'smart_device_type' => 'string',
        'smart_device_type_localized' => 'string',
        'reference' => 'string',
        'description' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'smart_device_id' => null,
        'smart_device_type' => null,
        'smart_device_type_localized' => null,
        'reference' => null,
        'description' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'smart_device_id' => 'SmartDeviceId',
        'smart_device_type' => 'SmartDeviceType',
        'smart_device_type_localized' => 'SmartDeviceTypeLocalized',
        'reference' => 'Reference',
        'description' => 'Description'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'smart_device_id' => 'setSmartDeviceId',
        'smart_device_type' => 'setSmartDeviceType',
        'smart_device_type_localized' => 'setSmartDeviceTypeLocalized',
        'reference' => 'setReference',
        'description' => 'setDescription'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'smart_device_id' => 'getSmartDeviceId',
        'smart_device_type' => 'getSmartDeviceType',
        'smart_device_type_localized' => 'getSmartDeviceTypeLocalized',
        'reference' => 'getReference',
        'description' => 'getDescription'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const SMART_DEVICE_TYPE_CAR = 'Car';
    const SMART_DEVICE_TYPE_HOME_DEVICE = 'HomeDevice';
    const SMART_DEVICE_TYPE_EV_CHARGER = 'EvCharger';
    const SMART_DEVICE_TYPE_BATTERY = 'Battery';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSmartDeviceTypeAllowableValues()
    {
        return [
            self::SMART_DEVICE_TYPE_CAR,
            self::SMART_DEVICE_TYPE_HOME_DEVICE,
            self::SMART_DEVICE_TYPE_EV_CHARGER,
            self::SMART_DEVICE_TYPE_BATTERY,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['smart_device_id'] = isset($data['smart_device_id']) ? $data['smart_device_id'] : null;
        $this->container['smart_device_type'] = isset($data['smart_device_type']) ? $data['smart_device_type'] : null;
        $this->container['smart_device_type_localized'] = isset($data['smart_device_type_localized']) ? $data['smart_device_type_localized'] : null;
        $this->container['reference'] = isset($data['reference']) ? $data['reference'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getSmartDeviceTypeAllowableValues();
        if (!is_null($this->container['smart_device_type']) && !in_array($this->container['smart_device_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'smart_device_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets smart_device_id
     *
     * @return string
     */
    public function getSmartDeviceId()
    {
        return $this->container['smart_device_id'];
    }

    /**
     * Sets smart_device_id
     *
     * @param string $smart_device_id smart_device_id
     *
     * @return $this
     */
    public function setSmartDeviceId($smart_device_id)
    {
        $this->container['smart_device_id'] = $smart_device_id;

        return $this;
    }

    /**
     * Gets smart_device_type
     *
     * @return string
     */
    public function getSmartDeviceType()
    {
        return $this->container['smart_device_type'];
    }

    /**
     * Sets smart_device_type
     *
     * @param string $smart_device_type smart_device_type
     *
     * @return $this
     */
    public function setSmartDeviceType($smart_device_type)
    {
        $allowedValues = $this->getSmartDeviceTypeAllowableValues();
        if (!is_null($smart_device_type) && !in_array($smart_device_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'smart_device_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['smart_device_type'] = $smart_device_type;

        return $this;
    }

    /**
     * Gets smart_device_type_localized
     *
     * @return string
     */
    public function getSmartDeviceTypeLocalized()
    {
        return $this->container['smart_device_type_localized'];
    }

    /**
     * Sets smart_device_type_localized
     *
     * @param string $smart_device_type_localized smart_device_type_localized
     *
     * @return $this
     */
    public function setSmartDeviceTypeLocalized($smart_device_type_localized)
    {
        $this->container['smart_device_type_localized'] = $smart_device_type_localized;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return string
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string $reference reference
     *
     * @return $this
     */
    public function setReference($reference)
    {
        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


