<?php
/**
 * EcedoERPCRMInterfaceReportModelSettlementInvoiceLetterSettlementInvoiceLetterEnergyDtoNewAdvancePaymentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo.ERP.UI.Web Core
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1-core
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EcedoERPCRMInterfaceReportModelSettlementInvoiceLetterSettlementInvoiceLetterEnergyDtoNewAdvancePaymentTest Class Doc Comment
 *
 * @category    Class
 * @description EcedoERPCRMInterfaceReportModelSettlementInvoiceLetterSettlementInvoiceLetterEnergyDtoNewAdvancePayment
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EcedoERPCRMInterfaceReportModelSettlementInvoiceLetterSettlementInvoiceLetterEnergyDtoNewAdvancePaymentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EcedoERPCRMInterfaceReportModelSettlementInvoiceLetterSettlementInvoiceLetterEnergyDtoNewAdvancePayment"
     */
    public function testEcedoERPCRMInterfaceReportModelSettlementInvoiceLetterSettlementInvoiceLetterEnergyDtoNewAdvancePayment()
    {
    }

    /**
     * Test attribute "advance_payment_id"
     */
    public function testPropertyAdvancePaymentId()
    {
    }

    /**
     * Test attribute "organization_id"
     */
    public function testPropertyOrganizationId()
    {
    }

    /**
     * Test attribute "has_advance_payment"
     */
    public function testPropertyHasAdvancePayment()
    {
    }

    /**
     * Test attribute "has_agreed_amount"
     */
    public function testPropertyHasAgreedAmount()
    {
    }

    /**
     * Test attribute "advance_payment_start_date"
     */
    public function testPropertyAdvancePaymentStartDate()
    {
    }

    /**
     * Test attribute "advance_payment_total_amount"
     */
    public function testPropertyAdvancePaymentTotalAmount()
    {
    }

    /**
     * Test attribute "advance_payment_total_amount_electricity"
     */
    public function testPropertyAdvancePaymentTotalAmountElectricity()
    {
    }

    /**
     * Test attribute "advance_payment_total_amount_gas"
     */
    public function testPropertyAdvancePaymentTotalAmountGas()
    {
    }

    /**
     * Test attribute "advance_payment_scheme"
     */
    public function testPropertyAdvancePaymentScheme()
    {
    }

    /**
     * Test attribute "advance_payment_annual_standard_usage"
     */
    public function testPropertyAdvancePaymentAnnualStandardUsage()
    {
    }
}
