<?php
/**
 * EcedoERPCRMInterfaceApiOpenMeasurementDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo.ERP.UI.Web Core
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1-core
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EcedoERPCRMInterfaceApiOpenMeasurementDataTest Class Doc Comment
 *
 * @category    Class
 * @description EcedoERPCRMInterfaceApiOpenMeasurementData
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EcedoERPCRMInterfaceApiOpenMeasurementDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EcedoERPCRMInterfaceApiOpenMeasurementData"
     */
    public function testEcedoERPCRMInterfaceApiOpenMeasurementData()
    {
    }

    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {
    }

    /**
     * Test attribute "netarea"
     */
    public function testPropertyNetarea()
    {
    }

    /**
     * Test attribute "responsible_party_ean"
     */
    public function testPropertyResponsiblePartyEan()
    {
    }

    /**
     * Test attribute "service_message"
     */
    public function testPropertyServiceMessage()
    {
    }

    /**
     * Test attribute "measurement_items"
     */
    public function testPropertyMeasurementItems()
    {
    }
}
