<?php
/**
 * EcedoERPCRMInterfaceApiInvoiceReasonResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo.ERP.UI.Web Core
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1-core
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EcedoERPCRMInterfaceApiInvoiceReasonResultTest Class Doc Comment
 *
 * @category    Class
 * @description EcedoERPCRMInterfaceApiInvoiceReasonResult
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EcedoERPCRMInterfaceApiInvoiceReasonResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EcedoERPCRMInterfaceApiInvoiceReasonResult"
     */
    public function testEcedoERPCRMInterfaceApiInvoiceReasonResult()
    {
    }

    /**
     * Test attribute "invoice_reason"
     */
    public function testPropertyInvoiceReason()
    {
    }

    /**
     * Test attribute "invoice_reason_localized"
     */
    public function testPropertyInvoiceReasonLocalized()
    {
    }

    /**
     * Test attribute "invoice_reason_value"
     */
    public function testPropertyInvoiceReasonValue()
    {
    }
}
