<?php
/**
 * EcedoERPCRMInterfaceApiEnergieleveringContractPostDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo.ERP.UI.Web Core
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1-core
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EcedoERPCRMInterfaceApiEnergieleveringContractPostDataTest Class Doc Comment
 *
 * @category    Class
 * @description EcedoERPCRMInterfaceApiEnergieleveringContractPostData
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EcedoERPCRMInterfaceApiEnergieleveringContractPostDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EcedoERPCRMInterfaceApiEnergieleveringContractPostData"
     */
    public function testEcedoERPCRMInterfaceApiEnergieleveringContractPostData()
    {
    }

    /**
     * Test attribute "meelift_proposition_reference"
     */
    public function testPropertyMeeliftPropositionReference()
    {
    }

    /**
     * Test attribute "start_reason"
     */
    public function testPropertyStartReason()
    {
    }

    /**
     * Test attribute "previous_contract_id"
     */
    public function testPropertyPreviousContractId()
    {
    }

    /**
     * Test attribute "channel"
     */
    public function testPropertyChannel()
    {
    }

    /**
     * Test attribute "sales_reference"
     */
    public function testPropertySalesReference()
    {
    }

    /**
     * Test attribute "billing_items"
     */
    public function testPropertyBillingItems()
    {
    }

    /**
     * Test attribute "contract_properties"
     */
    public function testPropertyContractProperties()
    {
    }

    /**
     * Test attribute "agreement_date"
     */
    public function testPropertyAgreementDate()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "proposition_reference"
     */
    public function testPropertyPropositionReference()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }
}
