<?php
/**
 * SysProfilesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo.ERP.UI.Web Core
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1-core
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SysProfilesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SysProfilesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for sysProfilesAddRowsToCustomProfile
     *
     * Voeg profielfracties toe aan een bestaand maatwerkprofiel.
     *
     */
    public function testSysProfilesAddRowsToCustomProfile()
    {
    }

    /**
     * Test case for sysProfilesCreateCustomProfile
     *
     * Aanmaken van een nieuw maatwerkprofiel.
     *
     */
    public function testSysProfilesCreateCustomProfile()
    {
    }

    /**
     * Test case for sysProfilesGetActiveProfiles
     *
     * Haal alle actieve maatwerkprofielen op.
     *
     */
    public function testSysProfilesGetActiveProfiles()
    {
    }

    /**
     * Test case for sysProfilesGetCustomProfile
     *
     * Haal een maatwerkprofiel op op basis van een id.
     *
     */
    public function testSysProfilesGetCustomProfile()
    {
    }
}
